name: Sync Past Leetcode Submissions
on:
  workflow_dispatch: # Allows you to trigger this manually with a button click

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Run LeetCode Sync
        uses: joshcai/leetcode-sync@v1.7
        with:
          github-token: ${{ github.token }}
          leetcode-csrf-token: ${{ secrets.LEETCODE_CSRF_TOKEN }}
          leetcode-session: ${{ secrets.LEETCODE_SESSION }}
          destination-folder: solutions
          # Force the action to scan your whole history
          skip-unsolved: true 
